### ISSUE TITLE
Keep running while window menu is open

### ISSUE THREAD

**Issue by 7890** [drobilla/pugl#11]
https://github.com/drobilla/pugl/blob/eada1042452e8708ca6c65f7c23ac3c59e4c53f0/pugl/pugl_win.c#L709

```
        case WM_ENTERSIZEMOVE:
        case WM_ENTERMENULOOP:
```

```
        case WM_EXITSIZEMOVE:
        case WM_EXITMENULOOP:
```

Eg. when context-clicking window border and menu opens, keep running like when window is moved or resized.

**Comment by drobilla** [comment]
I am not even sure it's worth the considerable effort to keep drawing while the Window is being dragged.  This stuff is a real nightmare on Windows.

I doubt just hooking in to those will make it work correctly, but I'll look into it.

**Comment by 7890** [comment]
It should work, I've tested it.
There's some rare cases left where the continuity is broken, but those two will make it almost complete.
I think it's reasonable to make it possible to run without any interruption in the view, independently of window actions, as much as possible.

**Comment by 7890** [comment]
Eventually related:
on Windows, when making a pugl view fullscreen the animation is halted but keyboard input is still procesed. After fiddling around, I found that this happens only when the view takes exactly the screen space (which is what fullscreen is supposed to do).
The workaround for now is to make the view 1 pixel wider than the screen. Funnily enough this does exactly the "right" thing. There must be something special going on when view is exactly the screen size that prevents to redraw if run with `-c`.

**Comment by 7890** [comment]
I saw this was addressed in
https://github.com/drobilla/pugl/commit/717668467c6c2d65c417e81f607977ed3d676863
+1
