### ISSUE TITLE
x11 excessive PUGL_EXPOSE even if minimized

### ISSUE THREAD

**Issue by 7890** [drobilla/pugl#15]
When running `pugl_test` continuously, PUGL_EXPOSE events are fired even if the application is minimized or behind another window. IIUC PUGL_EXPOSE shouldn't be fired if view isn't visible.
Compare to OSX: PUGL_EXPOSE is NEVER fired (potential bug)
Compare to Windows: PUGL_EXPOSE is not fired when minimized (as expected)

**Comment by 7890** [comment]
Not sure if this is the correct place:
https://github.com/drobilla/pugl/blob/908e249c8030698e4313df9aeb81cfb7763e5150/pugl/detail/x11.c#L573
The function can return directly,
`if(!view->visible)` or eventually `_NET_WM_STATE_HIDDEN` is set.
This turns down FPS to zero for hidden and minimized windows.

**Comment by 7890** [comment]
Eventually better: in x11.c `translateEvent`
```
case VisibilityNotify: //XVisibilityEvent, requires VisibilityChangeMask to be in eventMask
  view->visible = xevent.xvisibility.state==VisibilityFullyObscured ? false : true;
  break;
```
Then check for `view->visible` and only dispatch `PUGL_EXPOSE` when the window is at least partially visible to the user. Does that make sense?

**Comment by drobilla** [comment]
8fe6591 50f1188
