### ISSUE TITLE
Segmentation fault on macOS

### ISSUE THREAD

**Issue by rozaxe** [drobilla/pugl#2]
Hello,

I get a segmentation fault when running `pugl_cairo_test`. To build the app I used :

```
clang -framework Cocoa -framework OpenGL pugl_cairo_test.c pugl/pugl_osx.m -I./ `pkg-config --libs cairo` `pkg-config --cflags cairo`
```

I tried the various options `-r -i -g` and nothing changes, the same segmentation fault occurs.

I have succeed building and running `pugl_test` and displaying the colored triangle.

My specs :
- macOS High Sierra
- cairo 1.15.12

**Comment by drobilla** [comment]
Sorry about that, I let Cairo rot on MacOS as I was working on GL and more general portability things. 

Should be fixed in 20114f1 (which is always on GL under the hood).
