### ISSUE TITLE
x11 Clipboard Issue

### ISSUE THREAD

**Issue by 7890** [drobilla/pugl#24]
Using `pugl_test`, I can Ctrl+c in pugl window and paste this text into leafpad.
The other way around works too, but _only for short strings_. 
`Pugl test Pugl test Pugl test Pu` is the longest string that works, longer strings won't show up on Ctrl+v.
I wondered whether this is a local setting (X11..) that limits this, or a value that can be adjusted in pugl or eventually something else.
Can this behavior be confirmed for another installation? Thanks

**Comment by 7890** [comment]
https://github.com/drobilla/pugl/blob/master/pugl/detail/x11.c#L662
I found that the '8' in `XGetWindowProperty` call means 
`long_length | Specifies the length in 32-bit multiples of the data to be retrieved.`
Just setting this number to something larger made the limit go away. The question remains if this is a good place to set this or what would be an accurate value for most cases.

**Comment by drobilla** [comment]
2f422e1
