### ISSUE TITLE
pugl/cairo_gl.h not found

### ISSUE THREAD

**Issue by 7890** [drobilla/pugl#4]
Build on OSX fails:
```
[2/4] Compiling pugl/pugl_osx.m
../pugl/pugl_osx.m:22:10: fatal error: 'pugl/cairo_gl.h' file not found
#include "pugl/cairo_gl.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
```
Commenting the missing include out was enough for the build to go through, it could be a left-over from commit cf80f78f808e402d06dc891fce08b0f3b3865c15 (?)

**Comment by drobilla** [comment]
This was fixed in c18706e
