### ISSUE TITLE
Keyboard events not recognized (OSX)

### ISSUE THREAD

**Issue by 7890** [drobilla/pugl#5]
When running the pugl_test program, everything works for mouse, but keyboard input is ignored (eg. 'q'). The window seems to not get focus for keyboard input, key strokes are visible in the terminal. To rule out any ambiguity, it's not a start-up issue, I can click in the window or use switch tasks, it never gets keyboard input. This only happens on OSX, not on Linux.
Some advice would be appreciated. Thanks for making this useful library!

**Comment by drobilla** [comment]
This is a general Mac thing, GUI apps don't work properly unless they are in an app bundle.  The build system needs to be tinkered with to build things in the appropriate structure and add an `Info.plist` and so on.

**Comment by 7890** [comment]
I'll search in that direction, thanks for the pointer.

**Comment by 7890** [comment]
Adding pugl_test to an application bundle solved the problem, keyboard input works!
